name: Publish Helm Chart to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'selectel/**'
      - '!**.md'
jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.18.3'

      - name: Setup yq
        uses: mikefarah/yq@master

      - name: Get charts list
        run: charts_list=($(ls ./selectel))

      - name: Package Helm chart and push to GHCR
        run: |
          charts_list=($(ls ./selectel))
          for chart in "${charts_list[@]}"
              do
                chart_map_version[$chart]=$(helm show chart ./selectel/$chart | yq .version)
                echo $chart ${chart_map_version[$chart]}
                helm package ./selectel/${chart}
                helm push ${chart}-${chart_map_version[$chart]}.tgz oci://ghcr.io/${{ github.repository_owner }}
              done
